language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly
  
before_script:
  - composer self-update
  - composer install -n --prefer-source

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
